export type Contributor = {
  avatarUrl: string;
  displayName: string;
  githubHandle: string;
  profileUrl: string;
  sourceUrl: string;
};

export const contributors: readonly Contributor[] = [
  {
    avatarUrl: "https://github.com/GabryGao.png?size=160",
    displayName: "Xin Gao",
    githubHandle: "GabryGao",
    profileUrl: "https://github.com/GabryGao",
    sourceUrl: "https://github.com/GabryGao",
  },
  {
    avatarUrl: "https://github.com/wuyoscar.png?size=160",
    displayName: "Oscar Wu",
    githubHandle: "wuyoscar",
    profileUrl: "https://github.com/wuyoscar",
    sourceUrl: "https://github.com/wuyoscar/agent-oscar",
  },
  {
    avatarUrl: "https://github.com/SII-FLEEECERmw.png?size=160",
    displayName: "Ming Wen",
    githubHandle: "SII-FLEEECERmw",
    profileUrl: "https://github.com/SII-FLEEECERmw",
    sourceUrl: "https://github.com/SII-FLEEECERmw",
  },
  {
    avatarUrl: "https://github.com/bboylyg.png?size=160",
    displayName: "Yige Li",
    githubHandle: "bboylyg",
    profileUrl: "https://github.com/bboylyg",
    sourceUrl: "https://github.com/bboylyg",
  },
  {
    avatarUrl: "https://github.com/BeyonderXX.png?size=160",
    displayName: "Xiao Wang",
    githubHandle: "BeyonderXX",
    profileUrl: "https://github.com/BeyonderXX",
    sourceUrl: "https://github.com/BeyonderXX",
  },
  {
    avatarUrl: "https://github.com/chriskambimbi.png?size=160",
    displayName: "chris",
    githubHandle: "chriskambimbi",
    profileUrl: "https://github.com/chriskambimbi",
    sourceUrl: "https://github.com/chriskambimbi",
  },
  {
    avatarUrl: "https://github.com/CiaranZhou.png?size=160",
    displayName: "Yuhao Zhou",
    githubHandle: "CiaranZhou",
    profileUrl: "https://github.com/CiaranZhou",
    sourceUrl: "https://github.com/CiaranZhou",
  },
  {
    avatarUrl: "https://github.com/cmhzc.png?size=160",
    displayName: "Minghao Chang",
    githubHandle: "cmhzc",
    profileUrl: "https://github.com/cmhzc",
    sourceUrl: "https://github.com/cmhzc",
  },
  {
    avatarUrl: "https://github.com/CuteyThyme.png?size=160",
    displayName: "TTTTTiam",
    githubHandle: "CuteyThyme",
    profileUrl: "https://github.com/CuteyThyme",
    sourceUrl: "https://github.com/CuteyThyme",
  },
  {
    avatarUrl: "https://github.com/darius22222.png?size=160",
    displayName: "Jiahao Zhang",
    githubHandle: "darius22222",
    profileUrl: "https://github.com/darius22222",
    sourceUrl: "https://github.com/darius22222",
  },
  {
    avatarUrl: "https://github.com/Doby-Xu.png?size=160",
    displayName: "Hengyuan Xu",
    githubHandle: "Doby-Xu",
    profileUrl: "https://github.com/Doby-Xu",
    sourceUrl: "https://github.com/Doby-Xu",
  },
  {
    avatarUrl: "https://github.com/dongdongunique.png?size=160",
    displayName: "Yunhao Chen",
    githubHandle: "dongdongunique",
    profileUrl: "https://github.com/dongdongunique",
    sourceUrl: "https://github.com/dongdongunique",
  },
  {
    avatarUrl: "https://github.com/fresh-ma.png?size=160",
    displayName: "Zhouyuan_Ma",
    githubHandle: "fresh-ma",
    profileUrl: "https://github.com/fresh-ma",
    sourceUrl: "https://github.com/fresh-ma",
  },
  {
    avatarUrl: "https://github.com/HanxunH.png?size=160",
    displayName: "Hanxun Huang",
    githubHandle: "HanxunH",
    profileUrl: "https://github.com/HanxunH",
    sourceUrl: "https://github.com/HanxunH",
  },
  {
    avatarUrl: "https://github.com/haole1683.png?size=160",
    displayName: "Tianwei Song",
    githubHandle: "haole1683",
    profileUrl: "https://github.com/haole1683",
    sourceUrl: "https://github.com/haole1683",
  },
  {
    avatarUrl: "https://github.com/hldongml.png?size=160",
    displayName: "hldongml",
    githubHandle: "hldongml",
    profileUrl: "https://github.com/hldongml",
    sourceUrl: "https://github.com/hldongml",
  },
  {
    avatarUrl: "https://github.com/jamesxwang.png?size=160",
    displayName: "James Wang",
    githubHandle: "jamesxwang",
    profileUrl: "https://github.com/jamesxwang",
    sourceUrl: "https://github.com/jamesxwang",
  },
  {
    avatarUrl: "https://github.com/JerryLuo5799.png?size=160",
    displayName: "Jerry Luo",
    githubHandle: "JerryLuo5799",
    profileUrl: "https://github.com/JerryLuo5799",
    sourceUrl: "https://github.com/JerryLuo5799",
  },
  {
    avatarUrl: "https://github.com/jimmidier.png?size=160",
    displayName: "Jim Zheng [SSW]",
    githubHandle: "jimmidier",
    profileUrl: "https://github.com/jimmidier",
    sourceUrl: "https://github.com/jimmidier",
  },
  {
    avatarUrl: "https://github.com/L1lahKay.png?size=160",
    displayName: "Yihuan Chen",
    githubHandle: "L1lahKay",
    profileUrl: "https://github.com/L1lahKay",
    sourceUrl: "https://github.com/L1lahKay",
  },
  {
    avatarUrl: "https://github.com/l1teng.png?size=160",
    displayName: "Terry Li",
    githubHandle: "l1teng",
    profileUrl: "https://github.com/l1teng",
    sourceUrl: "https://github.com/l1teng",
  },
  {
    avatarUrl: "https://github.com/liushz.png?size=160",
    displayName: "liushz",
    githubHandle: "liushz",
    profileUrl: "https://github.com/liushz",
    sourceUrl: "https://github.com/liushz",
  },
  {
    avatarUrl: "https://github.com/luolin0715.png?size=160",
    displayName: "luolin0715",
    githubHandle: "luolin0715",
    profileUrl: "https://github.com/luolin0715",
    sourceUrl: "https://github.com/luolin0715",
  },
  {
    avatarUrl: "https://github.com/megaknight114.png?size=160",
    displayName: "Zonghuan Xu",
    githubHandle: "megaknight114",
    profileUrl: "https://github.com/megaknight114",
    sourceUrl: "https://github.com/megaknight114",
  },
  {
    avatarUrl: "https://github.com/mmxelio.png?size=160",
    displayName: "mmxelio",
    githubHandle: "mmxelio",
    profileUrl: "https://github.com/mmxelio",
    sourceUrl: "https://github.com/mmxelio",
  },
  {
    avatarUrl: "https://github.com/mttry.png?size=160",
    displayName: "Tingshu Mou",
    githubHandle: "mttry",
    profileUrl: "https://github.com/mttry",
    sourceUrl: "https://github.com/mttry",
  },
  {
    avatarUrl: "https://github.com/new60y.png?size=160",
    displayName: "hhhhhhhhhhhhhhhhhhhhh",
    githubHandle: "new60y",
    profileUrl: "https://github.com/new60y",
    sourceUrl: "https://github.com/new60y",
  },
  {
    avatarUrl: "https://github.com/oliviadzy.png?size=160",
    displayName: "Ziyun Dai",
    githubHandle: "oliviadzy",
    profileUrl: "https://github.com/oliviadzy",
    sourceUrl: "https://github.com/oliviadzy",
  },
  {
    avatarUrl: "https://github.com/Rosy0912.png?size=160",
    displayName: "Ruoxi Cheng",
    githubHandle: "Rosy0912",
    profileUrl: "https://github.com/Rosy0912",
    sourceUrl: "https://github.com/Rosy0912",
  },
  {
    avatarUrl: "https://github.com/SFTJBD.png?size=160",
    displayName: "Yifeng Gao",
    githubHandle: "SFTJBD",
    profileUrl: "https://github.com/SFTJBD",
    sourceUrl: "https://github.com/SFTJBD",
  },
  {
    avatarUrl: "https://github.com/SmallkeyChen.png?size=160",
    displayName: "SmallkeyChen",
    githubHandle: "SmallkeyChen",
    profileUrl: "https://github.com/SmallkeyChen",
    sourceUrl: "https://github.com/SmallkeyChen",
  },
  {
    avatarUrl: "https://github.com/snow-zhai.png?size=160",
    displayName: "snow-zhai",
    githubHandle: "snow-zhai",
    profileUrl: "https://github.com/snow-zhai",
    sourceUrl: "https://github.com/snow-zhai",
  },
  {
    avatarUrl: "https://github.com/StrawberryXia.png?size=160",
    displayName: "StrawberryXia",
    githubHandle: "StrawberryXia",
    profileUrl: "https://github.com/StrawberryXia",
    sourceUrl: "https://github.com/StrawberryXia",
  },
  {
    avatarUrl: "https://github.com/thom-wang.png?size=160",
    displayName: "Thom Wang [SSW]",
    githubHandle: "thom-wang",
    profileUrl: "https://github.com/thom-wang",
    sourceUrl: "https://github.com/thom-wang",
  },
  {
    avatarUrl: "https://github.com/Vinsonzyh.png?size=160",
    displayName: "Yunhan Zhao",
    githubHandle: "Vinsonzyh",
    profileUrl: "https://github.com/Vinsonzyh",
    sourceUrl: "https://github.com/Vinsonzyh",
  },
  {
    avatarUrl: "https://github.com/wang-jingyi.png?size=160",
    displayName: "zjuethan",
    githubHandle: "wang-jingyi",
    profileUrl: "https://github.com/wang-jingyi",
    sourceUrl: "https://github.com/wang-jingyi",
  },
  {
    avatarUrl: "https://github.com/wdrink.png?size=160",
    displayName: "Junke Wang",
    githubHandle: "wdrink",
    profileUrl: "https://github.com/wdrink",
    sourceUrl: "https://github.com/wdrink",
  },
  {
    avatarUrl: "https://github.com/Wwangb.png?size=160",
    displayName: "Zhixiang Wang",
    githubHandle: "Wwangb",
    profileUrl: "https://github.com/Wwangb",
    sourceUrl: "https://github.com/Wwangb",
  },
  {
    avatarUrl: "https://github.com/x-zheng16.png?size=160",
    displayName: "Xiang Zheng",
    githubHandle: "x-zheng16",
    profileUrl: "https://github.com/x-zheng16",
    sourceUrl: "https://github.com/x-zheng16",
  },
  {
    avatarUrl: "https://github.com/xbhuang23.png?size=160",
    displayName: "Xubin Huang",
    githubHandle: "xbhuang23",
    profileUrl: "https://github.com/xbhuang23",
    sourceUrl: "https://github.com/xbhuang23",
  },
  {
    avatarUrl: "https://github.com/xieyong0.png?size=160",
    displayName: "yongxie",
    githubHandle: "xieyong0",
    profileUrl: "https://github.com/xieyong0",
    sourceUrl: "https://github.com/xieyong0",
  },
  {
    avatarUrl: "https://github.com/xingjunm.png?size=160",
    displayName: "SII-Xingjun Ma",
    githubHandle: "xingjunm",
    profileUrl: "https://github.com/xingjunm",
    sourceUrl: "https://github.com/xingjunm",
  },
  {
    avatarUrl: "https://github.com/xinwong.png?size=160",
    displayName: "Xin Wang",
    githubHandle: "xinwong",
    profileUrl: "https://github.com/xinwong",
    sourceUrl: "https://github.com/xinwong",
  },
  {
    avatarUrl: "https://github.com/YiyingYang12.png?size=160",
    displayName: "Yiying Yang",
    githubHandle: "YiyingYang12",
    profileUrl: "https://github.com/YiyingYang12",
    sourceUrl: "https://github.com/YiyingYang12",
  },
  {
    avatarUrl: "https://github.com/yujq22.png?size=160",
    displayName: "Jiaqi Yu",
    githubHandle: "yujq22",
    profileUrl: "https://github.com/yujq22",
    sourceUrl: "https://github.com/yujq22",
  },
  {
    avatarUrl: "https://github.com/Yunhao-Feng.png?size=160",
    displayName: "YunhaoFeng",
    githubHandle: "Yunhao-Feng",
    profileUrl: "https://github.com/Yunhao-Feng",
    sourceUrl: "https://github.com/Yunhao-Feng",
  },
  {
    avatarUrl: "https://github.com/yxwang-10.png?size=160",
    displayName: "yixu wang",
    githubHandle: "yxwang-10",
    profileUrl: "https://github.com/yxwang-10",
    sourceUrl: "https://github.com/yxwang-10",
  },
  {
    avatarUrl: "https://github.com/zhangchaosd.png?size=160",
    displayName: "Chao Zhang",
    githubHandle: "zhangchaosd",
    profileUrl: "https://github.com/zhangchaosd",
    sourceUrl: "https://github.com/zhangchaosd",
  },
  {
    avatarUrl: "https://github.com/ZichanR.png?size=160",
    displayName: "ZichanR",
    githubHandle: "ZichanR",
    profileUrl: "https://github.com/ZichanR",
    sourceUrl: "https://github.com/ZichanR",
  },
  {
    avatarUrl: "https://github.com/zxwu.png?size=160",
    displayName: "zxwu",
    githubHandle: "zxwu",
    profileUrl: "https://github.com/zxwu",
    sourceUrl: "https://github.com/zxwu",
  },
] as const;
