// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from '/home/runner/work/opentaiweb.github.io/opentaiweb.github.io/node_modules/@umijs/renderer-react';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context: {} }, container);
}
