// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/homepage","redirect":"/","id":"1"},"2":{"path":"/","id":"2"},"3":{"path":"/riskDemo","id":"3"},"4":{"path":"/evaluation","id":"4"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.js')),
'3': React.lazy(() => import(/* webpackChunkName: "p__riskDemo__index" */'@/pages/riskDemo/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__evaluation__index" */'@/pages/evaluation/index.tsx')),
},
  };
}
